version: "3.9"

services:
  devops-microservice:
    build: .
    container_name: devops-microservice
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000